class PassReverser {
	/**
	 * @param {object} diffused diffusion dictionary
	 */
	constructor(diffused) {
		const json_raw = atob(diffused)
		const dictionary = JSON.parse(json_raw)

		this.diffused = dictionary
	}

	Reverse(input) {
		let reversed = ""

		let counters = {}
		const keys = Object.keys(this.diffused)
		for (let cnt = 0; cnt < keys.length; cnt++) {
			counters[keys[cnt]] = 0
		}

		for (let cnt = 0; cnt < input.length; cnt++) {
			let char = input[cnt]

			//avoid error
			if (counters[char] >= this.diffused[char].length) {
				counters[char] = 0
			}

			let adding = this.diffused[char][counters[char]]
			counters[char] += 1

			reversed += adding
		}

		return reversed
	}
}

const passReverser = new PassReverser(
	//hard code open key
	"eyIwIjpbImdnTks0USIsIjZHMFBqUSIsInJsVjUzVyIsIlNqQ2ZXMiIsIldNQzRkRCJdLCIxIjpbImlid3JYQSIsImgzM01UbSIsImd5dnA0UyIsIjA4Q3VNdCIsIkpZR1MyUyJdLCIyIjpbIjVQcHNkeCIsInNVVDlPYSIsImdkYUNqbiIsIjBqVjFSTiIsIlhCSloyYiJdLCIzIjpbImlKTE92QiIsImtmSVhUYiIsImFVVmZiVCIsIjM1ZUtMNCIsImwwZFMwbyJdLCI0IjpbIktSWFVTRVFQSFFMajBDVDMiLCJGNFU4Sk4iLCIwYUVrR2wiLCJmS1BUeHMiLCJrNDl5a00iXSwiNSI6WyI1NGhzeWgiLCJKd2NGSEMiLCJnbnR0bTQiLCJJYzRrT3MiLCJEMkh0bEIiXSwiNiI6WyI5MTQzc2IiLCJzOUVwdlciLCJiVlBoclAiLCJ4UkxPTHMiLCJvcTdkSG0iXSwiNyI6WyJadVREc28iLCJ0eGVhdG0iLCJGaFZjMTAiLCJmQ1g4RWkiLCI3SUEwQ1giXSwiOCI6WyJkcnBiOHoiLCJhUHVJSnYiLCJhVVhTMHYiLCJBZzVSV2UiLCJic0VpTFQiXSwiOSI6WyJJUnYzckwiLCJEWm13eEgiLCJiRmZSaFkiLCI4dXdkMG8iLCJ0aXhmdGgiXSwiYSI6WyJ3MGhxSFIiLCJrTHU2ZlQiLCJJVmtjSjIiLCI5YXRKRmJKRXJXTjlCNjc0IiwiQlN4a01LMlBTNjlvVVN5QiJdLCJiIjpbInppSXVxTSIsIndxb3JVSSIsIlNhUDBCdyIsIkV6RU12WiIsIjNDeXkxciJdLCJjIjpbIlZSRGk0OCIsImRFOEpleCIsImFvMnF3QyIsIlNyb3UxSCIsInFtYTV5NCJdLCJkIjpbIkhKQTBoQSIsInlkTEZ0c0ZsaWwzT3VVR2oiLCJPTzdSSWoiLCJPTDJ4SVMiLCI1YlJaWVIiXSwiZSI6WyJhelFra2oiLCJ2YUFXREoiLCJ3NEdFYk0iLCJzU3FBTjAiLCJaZDJxTWciXSwiZiI6WyJhZVZBQk8iLCIycWVSSzYiLCJzQ3U3RlgiLCI3RWdwS2wiLCJhVlpqTjQiXSwiZyI6WyJ2aXNpMnUiLCJzM2cwMUciLCJVN2lqQVIiLCJHbUtzTVgiLCJhcHNZU3oiXSwiaCI6WyJGVnFFWXUiLCJDRzZHNVciLCJwa3VzNTAiLCJhbml0Z0oiLCJpRnhVb0YiXSwiaSI6WyJpaTZQWnQiLCIwR0J4RDEiLCJnWml2bVMiLCJ0NTVUYUEiLCIyVE5nVU0iXSwiaiI6WyJEWHpTTVYiLCJWNWFmN2UiLCJPOUNwNDEiLCJHNUtmdEMiLCJzdUpJNUoiXSwiayI6WyIzUWdIUzUiLCI4SmY5clQiLCJYMHk4OUoiLCI0SlBDTlIiLCJXcThOR2giXSwibCI6WyJYQlZYNTUiLCI0cGFZeXoiLCJ4ZG9ReEIiLCJEUG5xNDciLCJoWlIyaUsiXSwibSI6WyJ6NFFyXzMiLCJ0a0xxWGlKQ1VEallrU01jIiwiNnVtSmw4IiwiM0JrMWhIIiwiVFBLOUZNIl0sIm4iOlsiVWhwSGxIIiwiM3c2ajRFIiwiZENXV0w2IiwiZGtraXo0IiwickI4NXJBIl0sIm8iOlsiWkkyWHRZIiwiTFhHalEzIiwiYm5UalI2IiwibG41a1B3IiwiaXA3UW9tIl0sInAiOlsiaUlVVlRVIiwiM1MzM1hFIiwiMENUbTA5IiwiSEZPM3h2IiwiUUNNOEN6Il0sInEiOlsiUGpOak9ZIiwiTDRmOGdTIiwiYmtOQVdKIiwiaHpVZ3I4IiwieE5hWHdRIl0sInIiOlsiTEtCOVpUIiwiQTNJeXltIiwiUHkwODF6IiwiOWticjI0IiwiQ3BPdDYwIl0sInMiOlsiY1oydUg4IiwiUjhKUExqIiwiZldtbG4yIiwiNVQ1bmNVIiwiSEJ3V1VUIl0sInQiOlsiVTRJbWU4IiwiTGtoSDBHIiwid1AzTEs1IiwiZ0NYMHVnIiwieDU5UHBrIl0sInUiOlsieVlQRDBWIiwiM3cyOEx6IiwiRUlaSjZXIiwiQVF6RklPIiwiYUFBeU1vIl0sInYiOlsiRGxIdlgyIiwiaG1UVUsyIiwiWHoyZkQ3IiwiZ2t0TVRIIiwieWtza2Z1Il0sInciOlsiNk1oeHozIiwiWVN4V1VpIiwiMExLaXZDIiwiYVVVMGdSIiwiT0tWRnhiIl0sIngiOlsiWWViTERhIiwiMFl4RW1BIiwiOXgwMTA0IiwiQ3F2dFBpIiwicVZRZ0p0Il0sInkiOlsiVFdFM01vIiwiNEkwcmRKIiwibDdvb3VWIiwiNGhueEhpIiwiVHRub0VoIl0sInoiOlsiOVBmR0llIiwiRUR5UXpaIiwiVEh2bWl5IiwiVWU2RW5DIiwiM1pBc3hPIl0sIkEiOlsidFQzMW81IiwicGVJdnNxIiwiSUN5ZTl3IiwiV2dHUTQ3IiwiVGVVbklyIl0sIkIiOlsiR3FRMWl1IiwiaXNheHNTIiwiWmpudmpGIiwiVXpwZkxKIiwid2RrNjRIIl0sIkMiOlsiSDNlWVJ1Iiwic2lkZEw5IiwicUl2RVB1IiwiblIxamhqIiwiZ0Q2N1pOIl0sIkQiOlsiWDMwT0ZyIiwiWFJUTkFwIiwiQW43bjhEIiwiY25WRjI4IiwiZ0E5MDFsIl0sIkUiOlsiQ0FjMmtXIiwiOVpCQWpuIiwibmU5aE01IiwiZ3J3QnJZIiwiRTJwVEx6Il0sIkYiOlsiZnNlUjJKIiwiVGxSNXVTIiwiNWdhdjRIIiwiVGJuVW5UIiwiWUszemNFIl0sIkciOlsicXFaMXVpIiwicW53THIzIiwiTlNKTFBJIiwiTUt2MHhhIiwiUDZadHRXIl0sIkgiOlsiZUpGMGtCIiwiUlc2MkdxIiwieU1PeEpkIiwicHpUSElqIiwiOVZqTUN1Il0sIkkiOlsiaGpiS0xYIiwiaW5YUGE0IiwiOXI1b04wIiwiTWNRcEVTIiwiMld0a0toIl0sIkoiOlsiSmpWM29QIiwiS2p4amJoIiwiOGs3dEZzIiwiUFBtVlNrIiwiRVhzM3ZMIl0sIksiOlsiQmdqVG9sIiwiSDdVV2lWIiwiNkg4SUpSIiwic3o3MmwyIiwiejc2TEV0Il0sIkwiOlsiZDhwN3BVIiwiNWxhRVdEIiwiUFh1b2hiIiwibzYwek5NIiwic3Y0OXpIIl0sIk0iOlsiZ2NSYUJpIiwiRVZESXFaIiwiMkpFWU1jIiwiaUlmQ3NzIiwiVlEwMk96Il0sIk4iOlsiZGNlcmF0IiwiU0VhRkZoIiwiYkRkWmZ0IiwiZUhwMkY2IiwiM01EVjJkIl0sIk8iOlsiWU9zbHdUIiwiWW1qNnZyIiwiTXpiWmR3IiwiWk1wQmg5IiwiZmVvVm9DIl0sIlAiOlsiaDR2Z1BlIiwidDdQVTZhIiwiMnFtUGRxIiwiQ2dhTUtQIiwiRG1GdzVYIl0sIlEiOlsid1JNaEJ3IiwiVjBaR1Q5IiwiZVpxQXI2IiwiMVVpbDZPIiwiZmFLcmZqIl0sIlIiOlsibjBqVG5ZIiwiWUtWOXNMIiwiZzZKNmdJIiwiQ09FWlNPIiwiRVdlUURNIl0sIlMiOlsia3VZcTJtIiwiU2VjMjR2IiwicDh0eXk4IiwieWF4ZVdCIiwiZkhKeHBNIl0sIlQiOlsidXVwUjBvIiwiYjA5TnlyIiwiWUpBa2t0IiwiRXhmMkF1IiwiSW55dDhEIl0sIlUiOlsiMTFBWUk0IiwiZ1duZTJHUFNqNEl1ZDYzMSIsIkFYem9jbiIsImk3SHNiWiIsImxOSHVIZyJdLCJWIjpbImJweVZLRSIsInVvbWJ3cCIsIlUwc3ZLNSIsIlV4V3hsdiIsIk1UODM0WiJdLCJXIjpbIkhiSUNEaiIsIjlodTEwdSIsInY0RXRVNiIsInIzS05uMyIsIm9tMzFjRyJdLCJYIjpbIkE0Rnh6ciIsImtCeU9DaiIsInR2NzU5YSIsImt0SXNHOCIsIlpnSVB3dSJdLCJZIjpbInBLRGE4biIsImxMOExhcCIsIldCNEYwSiIsInUwbXJWNSIsIkNUV3FGOCJdLCJaIjpbIklSWklnRiIsIngyZlRjUCIsIkx2OTdGRyIsInBYV0s5MyIsImVTUFRPZiJdfQ==",
)
