class PassReverser {
	/**
	 * @param {object} diffused diffusion dictionary
	 */
	constructor(diffused) {
		const json_raw = atob(diffused)
		const dictionary = JSON.parse(json_raw)

		this.diffused = dictionary
	}

	Reverse(input) {
		let reversed = ""

		let counters = {}
		const keys = Object.keys(this.diffused)
		for (let cnt = 0; cnt < keys.length; cnt++) {
			counters[keys[cnt]] = 0
		}

		for (let cnt = 0; cnt < input.length; cnt++) {
			let char = input[cnt]

			//avoid error
			if (counters[char] >= this.diffused[char].length) {
				counters[char] = 0
			}

			let adding = this.diffused[char][counters[char]]
			counters[char] += 1

			reversed += adding
		}

		return reversed
	}
}

const passReverser = new PassReverser(
	//hard code open key
	"eyIwIjpbIk5LZTlTSiIsImZNb3UxcyIsIlNod2g3MiIsImY5SDFaaCIsImxQWTdtZSJdLCIxIjpbIm9Pak4zOCIsIjNzMExTSyIsIjlpaHJqTSIsIk1pek5TNSIsImxOYWFVcCJdLCIyIjpbIlNZNDdINGl5b3QiLCJIOEtKdDciLCJUeWdKQUUiLCI5M3FQMUYiLCJTYjE1UDMiXSwiMyI6WyJZS0FLa0MiLCJvUlRlNmIiLCJtRDNBU3giLCJ3RUVPQkMiLCJKczNIVlkiXSwiNCI6WyJSN1VXT0MiLCJaU0hyNWciLCJ2U20wNGgiLCJ4RDF5N3MiLCJ3dEVTVlYiXSwiNSI6WyJsOEFGTDMiLCJqV2VSYmoiLCJlUExGT1UiLCJ2clJsZlQiLCJxNVNhMTYiXSwiNiI6WyIyWlM0OVgiLCJRZXdiQWgiLCJiRmY3SFoiLCJKT1QyY1UiLCJDVFFYbVIiXSwiNyI6WyJtTjZrWFoiLCIzanBKcWIiLCJDSFBROHQiLCJlN2dyOHEiLCJkRTQ5U2UiXSwiOCI6WyJsM3hVa20iLCJOQU5CQmIiLCI2VXQzM00iLCJMWWZSUTciLCJJNTNYZ2oiXSwiOSI6WyJVTW0xdkoiLCJvOGtyNGEiLCJLeHVoZXYiLCJ0MjlJYmMiLCJDUVYyUzMiXSwiYSI6WyJMOExCOHYiLCJBM3VBemYiLCJ5Q2wzczAiLCJhM3JIRjdYMVRIIiwibHl3WDU3WjQ0dSJdLCJiIjpbIlFvVnhPUyIsIlZDY0tDdiIsImpiMmh6RyIsIm1GbTNZRSIsIm1ZT09NTCJdLCJjIjpbImtzeElaRSIsIlI1SGhtaiIsIjNzNUI4SSIsIjNPeDlMUiIsIjRhYVZyZSJdLCJkIjpbIkhKQTB5aSIsIjNBS3FPZkpOZFgiLCJVWnlYOEYiLCJObjZUbloiLCJ1Rkp5eXAiXSwiZSI6WyJCZ0U2ZEwiLCJobHNSa0QiLCI0M1p0bVoiLCJOeGZUeFkiLCJUM0dtWnMiXSwiZiI6WyJIb1I2RWkiLCJiNUdpRU8iLCJIYWt1YkwiLCJZOEhnbHkiLCJocUVCNGQiXSwiZyI6WyJPRDdza28iLCJOODA1Z3YiLCIwVFRSNHoiLCI5TnpVbGQiLCJ5clRZSmMiXSwiaCI6WyI3aEd4YlIiLCJnU3l2RjUiLCJIekI0ajciLCJFYXN2Y2IiLCJrek94YWwiXSwiaSI6WyJaV2tXbEkiLCJLcWRoWk8iLCJVR1hxSnciLCIzZjdYcHEiLCJQamtJYkgiXSwiaiI6WyJVVkhHRHMiLCJDblc4ZXkiLCJjRExyT1ciLCIxZ1V3QkQiLCJOZXB4MUYiXSwiayI6WyJIQnQ4VFAiLCJtaEJOeEEiLCJxTFk3RnMiLCJVWHdIZmYiLCJCbmdic3ciXSwibCI6WyJuT0lVNEEiLCJ3Y3pvMDciLCJnemt0eTQiLCJUdWhXamwiLCJwSEszclciXSwibSI6WyJldXBWXzIiLCJmTEZPMkZCSFRLIiwibW4yVVk0IiwiRkc4alIwIiwidnhxWEpPIl0sIm4iOlsidHpqc2JOIiwibUI3Ujh6Iiwib3BoTnZtIiwidFlhZEVlIiwiMHN6clllIl0sIm8iOlsiQWFLZDFTIiwiUkFWWm1yIiwiTmkwMllhIiwidjc3dU5UIiwiVzdQNVZWIl0sInAiOlsiWEt3cFpOIiwiRm1KTGtyIiwiRW9zeHRRIiwidEJKZDA0IiwiR1p0ZXBHIl0sInEiOlsidXRucnZqIiwiS3FaaVZrIiwiM3RObkwwIiwibjBaWHlHIiwiT25MYzRrIl0sInIiOlsiYjBTVk44IiwiNGdVY3NaIiwid2xOM3dFIiwiMDBBeUhpIiwiVmlsR2lOIl0sInMiOlsiOHY1bFVGIiwianp1Z3dDIiwiVUphRTBuIiwiOGFpRERMIiwicVZlUGFQIl0sInQiOlsiVVF1Z0ZXIiwic0VwRTBxIiwiVVZNUGVjIiwiVEJWaE5OIiwidm10eEhhIl0sInUiOlsiRDgxWTduIiwid3pSdUxHIiwiRWpmTk5SIiwiMjdMbGtTIiwicHc0RGNDIl0sInYiOlsiUkRKc1diIiwiT3h3ak0xIiwibWpsSUI5IiwiRmYxZ3JDIiwiQ3FNdnJXIl0sInciOlsieXpQVUNQIiwiREVFV0p2IiwiS2JMdDQzIiwiVXlKcWFoIiwiY2l6b0FNIl0sIngiOlsiR085QTFSIiwiNUhxaVpaIiwiNnYzOGRLIiwiZ1p0UjRBIiwiZzVDRWNJIl0sInkiOlsia0FVaWxMIiwiV3Jnb1Q2IiwiM1k0Y0JOIiwiTXRUSFpBIiwiRlZmTG9iIl0sInoiOlsiY3U1dVhnIiwiWmhsUjY3IiwidmVLYkFMIiwiZUtOY1NGIiwiQllFWEMzIl0sIkEiOlsiZDFHQ2JvIiwiYzlKdUdLIiwiODRmdGVvIiwiZHNvREVSIiwiVnJOMFlQIl0sIkIiOlsiSDQwZGw0IiwiWWlROW1CIiwibXhnY29VIiwiYmsybVlGIiwicE12U1ptIl0sIkMiOlsiWFV0Vk9YIiwia1RDTGNSIiwiUXNCcWMxIiwiRjNpYUVlIiwiQWdEOGZCIl0sIkQiOlsiSDJSdWdPIiwiV0VycjRBIiwiZHRzWGpzIiwiZ2ROQUpoIiwicEEzZTlzIl0sIkUiOlsidlZ3clBCIiwiSTdqQWJGIiwiTkVsN1FLIiwibGU3YnZlIiwiSllWZE5wIl0sIkYiOlsiclNReE9KIiwibWZjb3dwIiwicWVobGtXIiwiNjhUQ1dGIiwiSFo4Uk1rIl0sIkciOlsiTExtOE5kIiwiWG81bXBiIiwiS1hLMnhJIiwidmliNjFrIiwiNnp3STU3Il0sIkgiOlsiSkRWZmhjIiwicDlyM1VhIiwicmlBYXZzIiwiQ29BejFkIiwiUVFWU2JCIl0sIkkiOlsiRHdtbDF2IiwiYlo0eHpnIiwiSlVNOVNyIiwiQlpIUk5NIiwiaUZTS3dZIl0sIkoiOlsiV21BS1dEIiwiNmJJM2QzIiwialJHQnpTIiwia1dvSUtXIiwidVdpSlpuIl0sIksiOlsibHBXSVJvIiwiWXFpeDBBIiwiVDFSWm9jIiwiNjM1cUZNIiwiVGtjOG5vIl0sIkwiOlsiRjZJaVRZIiwiWDNJWFZ2IiwicmdEYnhOIiwiVXhwemZDIiwiU0JOWXU2Il0sIk0iOlsiYTRiRERqIiwiRmNuQktjIiwienFyQVFKIiwiRmtvQmJmIiwiMkNBblZHIl0sIk4iOlsiYmpYR1gyIiwicUduU3g2IiwiYlJFbVJ4IiwiMEp5MWJZIiwiMHBoU1ROIl0sIk8iOlsiZUhlOWpvIiwiTnNWd255IiwiQmxNVmJNIiwiRjE1NmJiIiwiRG1GNlR0Il0sIlAiOlsiWXBzYlJSIiwieTdHeHd3Iiwib1lqTEl6IiwiSmdYbUQ4IiwiWTdsYXBaIl0sIlEiOlsiSnRmU2tkIiwiaUF3UG9hIiwiUFoyS0RMIiwiaHd3Z0RKIiwieTJ2RjlIIl0sIlIiOlsiUkxGbmoyIiwiVFNKMUtvIiwiUzFwS1ZTIiwiTW9nTG1vIiwiYWlHcmNsIl0sIlMiOlsia3kzZk1CIiwiMWNQY0VSIiwiOGYwVDRrIiwiYkFON2JHIiwiVU5kSHlpIl0sIlQiOlsiRnpjWmFhIiwidzZJM0I0IiwibU9nMHpCIiwiU2VBWjN6IiwicUdrNHN6Il0sIlUiOlsiMTFBWUk0IiwiWUZxeVU2UlNoaSIsIkNodDRHQSIsInlsN1NMVSIsInc5TXplUyJdLCJWIjpbIjhZZ0RWQSIsIjREMXJ1MSIsIkFCb25VbCIsImE4UkJudiIsIkl1UFZCaSJdLCJXIjpbImh4aXlxUCIsIldHUVlhcSIsInFJSHRzZCIsIk1kRW5QRSIsInU4ckg2RyJdLCJYIjpbImNNRUVrdCIsImNBRUhQSCIsIldnYkR6TiIsIm9scVN2YSIsIk5JdzR6dSJdLCJZIjpbInJMREFNcyIsIlg5YWRDcCIsIjVsRnV0SCIsIjQyS1ROaSIsIno3ck16WCJdLCJaIjpbIjh1a0laNCIsIlpZNGg4SCIsIlJkSzE3OCIsInhWY2xLQyIsIlNTV1ZsdCJdfQ==",
)
