class PassReverser {
	/**
	 * @param {object} diffused diffusion dictionary
	 */
	constructor(diffused) {
		const json_raw = atob(diffused)
		const dictionary = JSON.parse(json_raw)

		this.diffused = dictionary
	}

	Reverse(input) {
		let reversed = ""

		let counters = {}
		const keys = Object.keys(this.diffused)
		for (let cnt = 0; cnt < keys.length; cnt++) {
			counters[keys[cnt]] = 0
		}

		for (let cnt = 0; cnt < input.length; cnt++) {
			let char = input[cnt]

			//avoid error
			if (counters[char] >= this.diffused[char].length) {
				counters[char] = 0
			}

			let adding = this.diffused[char][counters[char]]
			counters[char] += 1

			reversed += adding
		}

		return reversed
	}
}

const passReverser = new PassReverser(
	//hard code open key
	"eyIwIjpbIkhtZVpnMCIsImtMOTkwbSIsIkRSUm5NcSIsInppeW9IYyIsImN3YWdYZiJdLCIxIjpbIkxHaEN2WSIsInlVTFlPMiIsIm43UVlIRSIsImJXQ21HUSIsInI5VU5tbSJdLCIyIjpbIkJMMDZ1QjFxemMiLCJqa2E0UDYiLCJDSFlyQlgiLCIzZ0l0MGwiLCJXem53RjQiXSwiMyI6WyJFZFBVbHoiLCJpMEEyNjgiLCJraGw3UjAiLCJBSEt0eUgiLCI4RllkY1giXSwiNCI6WyJZWTU1QVgiLCJvNFhEZDkiLCJnSk1BbmsiLCJrOWFsOEkiLCJ4QXVvaEsiXSwiNSI6WyI1c0JtMDYiLCJralhjVUIiLCIxS0pTMEgiLCJwMGRYZksiLCJQa1RKOG0iXSwiNiI6WyJnOUJQak4iLCJpQXdsTXMiLCJRZFNOTTIiLCJQMXBKOFIiLCJENWtmUU0iXSwiNyI6WyJvOHZXSXgiLCJzOVJBd0YiLCJBSkdPa1YiLCJKeFlTSVQiLCJ2RTl4VEIiXSwiOCI6WyI2WTFaQzgiLCJNSlJKS0EiLCJmV0JkN1MiLCJuSTNmSVoiLCJTdGRnTnkiXSwiOSI6WyJXcW1MMkEiLCIxOGxHZEoiLCJMR1Z4TmYiLCI3NXNKZWYiLCJPbk03N1EiXSwiYSI6WyJpUk5UZUgiLCJEbndTQ3YiLCJYOVk0Wk8iLCJ0SDA3eGVvM2J3Iiwic1dUNW5MdGhoRCJdLCJiIjpbImRxdkhXNyIsIlptSUZ3MCIsInREUFVTeiIsIml1OVBqTiIsIm51SGZ4ciJdLCJjIjpbImJDVVlEZCIsIk4zUXNPQyIsIkE1UWVQNiIsIjFqZkJ5TCIsIjRTdlFMRSJdLCJkIjpbIkhKQTBmTCIsIktqM21JdmJscmkiLCJteU5IUVIiLCJoTjRXcWgiLCJKenpaYjEiXSwiZSI6WyJIc0NUSDEiLCJhR1l1elYiLCJJT2RuTWkiLCJBQlZvUnUiLCI2UmxZc1ciXSwiZiI6WyIzSVp5RDMiLCJyZ2xWdmciLCJoM2lUYUQiLCJPV1htMEMiLCJFcTFOMWMiXSwiZyI6WyIza3hvNUYiLCJsTGtTY0oiLCJOME4xaDQiLCI5aHVOcVQiLCJKQmVrQ00iXSwiaCI6WyJiUTlrQlQiLCJqNExIeHAiLCJHZFJhbHAiLCJMSWNxVmEiLCI1VFFyaWIiXSwiaSI6WyJONHBFWmIiLCJKUWxSNlkiLCJnUmd0M3QiLCJXQXB5S1QiLCJET0pWVDgiXSwiaiI6WyJIbU9zRzIiLCJLRzdNZXYiLCJUZHFnOTMiLCJJVkFFRWciLCJmUHg2aFIiXSwiayI6WyJzS1RqYkkiLCJhTlNWczMiLCJzNjhxekkiLCJIdmJuczkiLCJ1ZzdwNlIiXSwibCI6WyJ1MGtubUwiLCI2Zlk4M2UiLCJFVDQ2bEMiLCJRSHV5bmMiLCJPS1EwVksiXSwibSI6WyJkUm81X1UiLCI1MVU2MkJ3VGhDIiwiaElaNzlhIiwiazJ6OVdyIiwiMDVzRW1UIl0sIm4iOlsiV3MwQTdQIiwiREJlc0FuIiwiNUNNc0dvIiwiMHhXRUF4IiwidzJBRWVDIl0sIm8iOlsiUlg2bXhhIiwibGZudFBJIiwiZ1JGZFNoIiwiVVpmanZmIiwiNHFDY1hVIl0sInAiOlsidk5oSVA0IiwiTTlYZVBGIiwiWFR6MTcxIiwiWVdFU0JSIiwiR0kxUGVBIl0sInEiOlsicTVPS05pIiwiaTRxU3lCIiwiWVFkRVdEIiwicWpyb0o5IiwicUNnakY4Il0sInIiOlsiUFZ5MlZxIiwiRzliYldkIiwiUWlzTkpUIiwiRWMwQ25RIiwiVkQ5NXZBIl0sInMiOlsibUlwQnVWIiwiY2F4bVNpIiwiUm1DTzlXIiwiTXBFdWNJIiwibEZIc3F4Il0sInQiOlsiR0treWNzIiwiS1o0QTMyIiwiZVVRS2JLIiwiUVNTNmswIiwiemhsWVNtIl0sInUiOlsiZWJaQllGIiwiM1lrRGhqIiwiTFFvdVBRIiwiOEhiMFM2Iiwia3pGYk9oIl0sInYiOlsib3VvMTFWIiwiZTNMM0RXIiwiSVhONTNUIiwiZnhNdHRmIiwiVGEyZHRBIl0sInciOlsicjlIMkd0IiwiV3VwR0pXIiwiclVjZG5xIiwic3J1NzVVIiwiVG83bHZNIl0sIngiOlsiNGF0Sk9xIiwiUVJ4VmhrIiwiRHZHWEpiIiwiSjFlR2RwIiwia05TdkdzIl0sInkiOlsiazFRQ0ROIiwiVHBLeGdrIiwiNExjVGFVIiwiMUtBR0prIiwieHZRMFpiIl0sInoiOlsiNUxrSUtVIiwiNzRlYkpCIiwiNTZNMWR3IiwidWdPVzFIIiwiQmw4SUJZIl0sIkEiOlsianZyYmxnIiwidWxXZm1pIiwib3JaYmhrIiwiZzg2NXloIiwiZHlNelBTIl0sIkIiOlsidUtsdkVJIiwiRDlDNHc3IiwiVEphakJrIiwid0lBUkV4IiwiVjlOOGwzIl0sIkMiOlsiYnY3Q0hXIiwiR3NhZjBsIiwiaVJGekROIiwiWmlIRnA1IiwiUXo2SVRxIl0sIkQiOlsiVzdYYjAwIiwiNmxzZ0g1IiwiZ0pnWGRsIiwiNGJDMXA2IiwiUE9YcTZDIl0sIkUiOlsiM2ZDQTJvIiwiSlJ0ejh2IiwiQUgwTnJlIiwiS0JQeVVzIiwiS0FrbzhBIl0sIkYiOlsicHpsT2JEIiwiMGo3cUZhIiwiT3FSd0NXIiwibjZUZWlwIiwiWlFkMWxIIl0sIkciOlsiaTBPTlJaIiwiYUZjYlNuIiwiQmFsdzBSIiwiSkVMRG9hIiwiNVBRNmRvIl0sIkgiOlsiTmFPOHpnIiwiMUFCb3MxIiwiQ29heVJoIiwiQlF6UnNmIiwiMHBXU3lCIl0sIkkiOlsiRUEyMjRhIiwibnFYVkttIiwiVkJzMjJ2IiwieWh2a09EIiwiRGZvSFBpIl0sIkoiOlsibk1iaVQ2IiwiblZEMWloIiwiQ25yYldkIiwiSDFZMUZOIiwiM2lKNHhpIl0sIksiOlsiTjlpVjViIiwiSlA2UDRNIiwidUhnd3FHIiwia1dabUQyIiwiOXQ0d0JaIl0sIkwiOlsiNkFqOHIwIiwiSDB0WU9nIiwiTzVvY21GIiwiTXRpd0hPIiwiSENRZnpPIl0sIk0iOlsiMFZCVURXIiwidVJZekpzIiwiYUxFVWU5IiwiMUhQV1hzIiwiR3YxMEJDIl0sIk4iOlsiV1UzYW13IiwidWw0b2VyIiwiRVBVSXFWIiwidGRHd1NiIiwiZjdUcWU0Il0sIk8iOlsidEw5RnMzIiwic0MyMDRHIiwidWVJNTFaIiwiMU8zVFl3IiwiQUFlNGtIIl0sIlAiOlsiMTZVY1pZIiwidXo0N3hlIiwiTjB2UzVJIiwiU25veWxyIiwiODdrTlhKIl0sIlEiOlsiZDBBNUZiIiwiYldhcTY4IiwiMlRiemlHIiwiaE5NNlhCIiwiN015NWtSIl0sIlIiOlsidDl5cXhtIiwiWGY0bVNCIiwib2pKZzloIiwiNGNpaDNKIiwiYmUwRWJ4Il0sIlMiOlsiYm13U0NCIiwiUmhKbFQyIiwieW9rcmN3IiwiTW9XOFF1IiwicGEzdmVKIl0sIlQiOlsiUEhtOG1YIiwiQ2VCTFh2IiwiUDc5ckhXIiwiOFJYRjU5IiwiYUF0S0EyIl0sIlUiOlsiMTFBWUk0IiwiYjVvSXNZbElvdiIsIndaV2V0ViIsIlRsbWptSyIsIlNlOWZGTiJdLCJWIjpbIktQTHQwUCIsIm5MOHliWCIsIm1iYU0xbyIsIks0SlVBTiIsInl1TkViMSJdLCJXIjpbInhjT2dEUyIsIm1NMjdOQyIsIldTUElLeCIsIjVJcExQeCIsIlU3N2NMWiJdLCJYIjpbImg3Q1FJcyIsIjRNRFlTdSIsIkZKR3h1byIsImoyYTJwdSIsIjRJQXJITSJdLCJZIjpbIktFSUZPSCIsIlZSYVl0OCIsInRkVnhtUSIsIkVEcmxuayIsIkJvaWRPQiJdLCJaIjpbIlQ3SnZPYiIsImFGWEFSRiIsIjBTRnBjeiIsInNKbHZVMSIsIkdLTVQ4dSJdfQ==",
)
